<?php

// @codingStandardsIgnoreFile

/** @var \WeltPixel\AdvancedWishlist\Block\WishlistAddto $block */
$isMultiWishslitEnabled = $block->isMultiWishlistEnabled();
$isAjaxWishslitEnabled = $block->isAjaxWishlistEnabled();

/** @var \WeltPixel\AdvancedWishlist\Helper\Data $_helper */
$_helper = $this->helper('WeltPixel\AdvancedWishlist\Helper\Data');
$cspNonceProvider = $_helper->getCspNonceProvider();
?>
<?php if ($isMultiWishslitEnabled) : ?>
<div class="multiple-wishlists-selector-container">
    <select class="wp-wishlist-selector" name="wp-multi-wishlist-id">
    </select>
</div>
<script<?php if ($cspNonceProvider) : ?> nonce="<?= $block->escapeHtmlAttr($cspNonceProvider->generateNonce()); ?>"<?php endif; ?>>
    requirejs(['jquery',  'WeltPixel_AdvancedWishlist/js/weltpixel_wishlist_addto'],
        function   ($, wishlistAddTo) {
            $(document).ready(function() {
                wishlistAddTo.initMultiWishlist({
                    getWishlistsUrl: "<?= $block->escapeJs($block->escapeUrl($block->getUrl('wp_collection/multiwishlist/get', ['_secure' =>  true]))) ?>",
                    ajaxWishlist: <?php /* @noEscape */ echo $isAjaxWishslitEnabled ? 'true' : 'false'; ?>
                });
            });
        });
</script>
<?php elseif ($isAjaxWishslitEnabled) :?>
<script<?php if ($cspNonceProvider) : ?> nonce="<?= $block->escapeHtmlAttr($cspNonceProvider->generateNonce()); ?>"<?php endif; ?>>
    requirejs(['jquery',  'WeltPixel_AdvancedWishlist/js/weltpixel_wishlist_addto'],
        function   ($, wishlistAddTo) {
            $(document).ready(function() {
                wishlistAddTo.initAjaxWishlist({
                    ajaxWishlist: true
                });
            });
        });
</script>
<?php endif; ?>
